-- MySQL Script generated by MySQL Workbench
-- Fri Feb 21 21:45:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `identification_type` VARCHAR(50) NOT NULL,
  `identification` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bank`.`Account_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Account_type` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bank`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Country` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` CHAR(2) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bank`.`Bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Bank` (
  `id` INT(11) NOT NULL,
  `code` VARCHAR(5) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `Country_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identification_code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_Bank_Country1_idx` (`Country_id` ASC) VISIBLE,
  CONSTRAINT `fk_Bank_Country1`
    FOREIGN KEY (`Country_id`)
    REFERENCES `bank`.`Country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bank`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Branch` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `identification_code` CHAR(4) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Bank_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identification_code_UNIQUE` (`identification_code` ASC) VISIBLE,
  INDEX `fk_Branch_Bank1_idx` (`Bank_id` ASC) VISIBLE,
  CONSTRAINT `fk_Branch_Bank1`
    FOREIGN KEY (`Bank_id`)
    REFERENCES `bank`.`Bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bank`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Account` (
  `id` INT(11) NOT NULL,
  `number` INT(10) UNSIGNED NOT NULL,
  `balance` DOUBLE NOT NULL,
  `iban` VARCHAR(45) NOT NULL,
  `Customer_id` INT(11) NOT NULL,
  `Account_type_Id` INT(11) NOT NULL,
  `Branch_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iban_UNIQUE` (`iban` ASC) VISIBLE,
  INDEX `fk_Account_Customer_idx` (`Customer_id` ASC) VISIBLE,
  INDEX `fk_Account_Account_type1_idx` (`Account_type_Id` ASC) VISIBLE,
  INDEX `fk_Account_Branch1_idx` (`Branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Customer`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `bank`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_Account_type1`
    FOREIGN KEY (`Account_type_Id`)
    REFERENCES `bank`.`Account_type` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_Branch1`
    FOREIGN KEY (`Branch_id`)
    REFERENCES `bank`.`Branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bank`.`Transaction_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Transaction_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bank`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Transaction` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `amount` DOUBLE NOT NULL,
  `Account_id` INT(11) NOT NULL,
  `Transaction_Type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Transaction_Account1_idx` (`Account_id` ASC) VISIBLE,
  INDEX `fk_Transaction_Transaction_Type1_idx` (`Transaction_Type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transaction_Account1`
    FOREIGN KEY (`Account_id`)
    REFERENCES `bank`.`Account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_Transaction_Type1`
    FOREIGN KEY (`Transaction_Type_id`)
    REFERENCES `bank`.`Transaction_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
